SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) as SCORE
    FROM REST_INFO as I
        JOIN REST_REVIEW as R ON I.REST_ID = R.REST_ID AND I.ADDRESS LIKE '서울%'
    GROUP BY I.REST_ID
    ORDER BY SCORE DESC, I.FAVORITES DESC;