SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
    FROM ITEM_INFO as I
        JOIN ITEM_TREE as T ON I.ITEM_ID = T.ITEM_ID
    WHERE T.PARENT_ITEM_ID IN (
        SELECT ITEM_ID
            FROM ITEM_INFO
            WHERE RARITY = 'RARE'
        )
    ORDER BY I.ITEM_ID DESC;